version: '3'
services:
  discovery:
    image: directory
    build:
      context: ./discovery
      dockerfile: Dockerfile
    ports:
      - "8761:8761" # back
    container_name: directory

  config-server:
    image: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888" #metier
    container_name: config-server

  srv-discovery:
    image: srv-discovery
    build:
      context: ./srv-discovery
      dockerfile: Dockerfile
    ports:
      - "5678:5678" #front:5432
    container_name: srv-discovery

  gateway:
    image: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "9090:9090" # front.new
    container_name: gateway