version: '3'
services:
  discovery:
    image: directory
    build:
      context: ./discovery
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    container_name: directory

  config-server:
    image: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    container_name: config-server

  srv-discovery:
    image: srv-discovery
    build:
      context: ./srv-discovery
      dockerfile: Dockerfile
    ports:
      - "5678:5678"
    container_name: srv-discovery

  gateway:
    image: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    container_name: gateway