version: '3'
services:
  suivis:
    image: suivis
    build:
      context: ./suivis
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    container_name: suivis

  utilisateurs:
    image: utilisateurs
    build:
      context: ./users
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    container_name: utilisateurs
