version: '3'
services:
  discovery:
    image: directory
    build:
      context: ./discovery
      dockerfile: Dockerfile
    ports:
      - "82:8761" #
    container_name: directory

  config-server:
    image: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "81:8888"
    container_name: config-server

  srv-discovery:
    image: srv-discovery
    build:
      context: ./srv-discovery
      dockerfile: Dockerfile
    ports:
      - "5432:5678"
    container_name: srv-discovery

  gateway:
    image: gateway
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "8000:9090" # front.new
    container_name: gateway