security.basic.enable: false
management.security.enabled: false
spring:
  profiles:
    active: git
  cloud:
      server:
        git:
         uri: https://github.com/achillesimo/montres
         basedir: services-configuration
