security.basic.enable: false
management.security.enabled: false
spring:
  profiles:
    active: git
  cloud:
      server:
        git:
         username: achillesimo
         password: Mathes13
         uri: https://github.com/achillesimo/montres
         searchPaths: services-configuration
