spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
routes:
- id: suivi-un
  uri: suivi
  predicates:
  - Path=**api/suivis/user


eureka:
  client:
    serviceUrl:
      defaultZone: http://directory:8761/eureka
    register-with-eureka: true
    fetch-registry: true