server:
  port: 8083
  servlet:
    context-path: "/api"

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  h2:
    console:
      enabled: true
  devtools:
    livereload:
      enabled: true
  jpa:
    show-sql: true
    database: h2
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect

eureka:
  client:
    serviceUrl:
      defaultZone: http://directory:8761/eureka
    register-with-eureka: true
    fetch-registry: true