server:
  port: 5678
spring:
  application:
    name: sidecar

sidecar:
  port: 3000
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://195.154.81.212:8761/eureka
    register-with-eureka: true
    fetch-registry: true