
  server:
    port: 5678
  spring:
    application:
      name: sidecar

  eureka:
    client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
      register-with-eureka: true
      fetch-registry: true

  sidecar:
    port: 3000

    
management:

  endpoints:
    web:
      exposure:
        include: "*"
